language: csharp
solution: Raymond.Costco.Web.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore Raymond.Costco.Web.sln

script:
  - xbuild Raymond.Costco.Web.sln /p:Configuration=debug 
